travelnest/app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('dangky/', views.dangky, name = "dangky"),
    path('dangnhap/', views.dangnhap, name = "dangnhap"),
    path('logout/', views.logoutPage, name = "logout"),
    path('', views.home, name = "home"),
    # path('', views.index, name='index'),
    path('ds/', views.ds, name = "ds"),
    path('ks/', views.ks, name = 'ks'),
    path('search/', views.search, name = 'search'),
    path('datphong/', views.datphong, name = "datphong"),
    path('dondatphong/', views.dondatphong, name = "dondatphong"),
    path('custom-dashboard/', views.index, name='custom_dashboard'),
    # path('custom-profile/', views.profile, name='custom_profile'),
    path('customer-dashboard/', views.dashboard, name='customer_dashboard'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
     path('nammoi/', views.nammoi),
]

travelnest/travelnest/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('app.urls')),
    path('', include('admin_argon.urls')),
]
urlpatterns +=static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

travelnest/app/models.py
from django.db import models
# from .models import User
from django.contrib.auth.models import AbstractUser
# from django.contrib.auth.forms import UserCreationForm

# Create your models here.
class User(AbstractUser):
    phone_number = models.CharField(max_length=20,null=True)
    address = models.CharField(max_length=200,null=True)
    avatar = models.ImageField(null=True,blank=True)

    def __str__(self):
        return self.username

# class MyCreateUserForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username','email','first_name','last_name','password1','password2']

class Tinh(models.Model):
    tentinh = models.CharField(max_length=200,null=True)
    anhtinh = models.ImageField(null=True,blank=True)
    def __str__(self):
        return self.tentinh
class KhachSan(models.Model):
    tenkhachsan = models.CharField(max_length=200,null=True)
    diachi = models.CharField(max_length=200,null=True)
    sdt = models.CharField(max_length=200,null=True)
    mota = models.CharField(max_length=200,null=True)
    email_ks = models.CharField(max_length=200,null=True)
    tinh = models.ForeignKey(Tinh,on_delete=models.SET_NULL,blank=True,null=True)
    anhkhachsan = models.ImageField(null=True,blank=True)
    ngay_them = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    def __str__(self):
        return self.tenkhachsan
    @property
    def diem_trung_binh(self):
        danhgia_list = Danhgia.objects.filter(phong__khachsan=self)
        # Tính tổng điểm từ tất cả các đánh giá
        tong_diem = sum([danhgia.diem for danhgia in danhgia_list])
        # Đếm số lượng đánh giá
        so_luong_danh_gia = danhgia_list.count()
        # Tính điểm trung bình hoặc đặt điểm mặc định là 10 nếu chưa có đánh giá
        diem_trung_binh = (tong_diem / so_luong_danh_gia) if so_luong_danh_gia > 0 else 10
        diem_tb= int(diem_trung_binh)
        return diem_tb
    @property
    def get_danh_gia_tb(self):
        if self.diem_trung_binh == 10:
            return "Tuyệt vời"
        elif self.diem_trung_binh == 8:
            return "Tốt"
        elif self.diem_trung_binh == 7:
            return "Tạm ổn"
        elif self.diem_trung_binh == 5:
            return "Không tốt"
    @property
    def sum_danh_gia(self):
         danhgia_list = Danhgia.objects.filter(phong__khachsan=self)
         so_luong_danh_gia = danhgia_list.count()
         return so_luong_danh_gia
class LoaiPhong(models.Model):
    tenloaiphong = models.CharField(max_length=200,null=True)
    mota_loaiphong = models.CharField(max_length=200,null=True)
    def __str__(self):
        return self.tenloaiphong
class Phong(models.Model):
    loaiphong = models.ForeignKey(LoaiPhong,on_delete=models.SET_NULL,blank=True,null=True)
    loaigiuong = models.CharField(max_length=200,null=True)
    mota = models.CharField(max_length=200,null=True)
    dientich = models.CharField(max_length=200,null=True)
    phongtam = models.CharField(max_length=200,null=True)
    soluongnguoi = models.IntegerField()
    giaphong = models.FloatField()
    trangthaiphong = models.CharField(max_length=200,null=True)
    khachsan = models.ForeignKey(KhachSan,on_delete=models.SET_NULL,blank=True,null=True)
    def is_phong_trong_hien_tai(self, ngaynhan, ngaytra):
        ngay_da_dat =True
        cac_dat_phong = ChiTietHoaDon.objects.filter(phong=self)
        # Kiểm tra xem ngày hiện tại có nằm trong bất kỳ khoảng đặt phòng nào không
        for dat_phong in cac_dat_phong:
            ngay_nhan = dat_phong.ngay_gio_nhan.date()
            ngay_tra = dat_phong.ngay_gio_tra.date()
            if  not (ngay_nhan > ngaytra or ngay_tra < ngaynhan):
                ngay_da_dat = False  # Phòng trống
        return ngay_da_dat

class Anh(models.Model):
    anhphong = models.ImageField(null=True,blank=True)
    phong = models.ForeignKey(Phong,on_delete=models.SET_NULL,blank=True,null=True )
class Danhgia(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    phong = models.ForeignKey(Phong,on_delete=models.SET_NULL,blank=True,null=True)
    diem = models.IntegerField()
    binhluan = models.CharField(max_length=200,null=True)
    ngay_danhgia = models.DateTimeField(auto_now_add=True)
    @property
    def get_danh_gia(self):
        if self.diem == 10:
            return "Tuyệt vời"
        elif self.diem == 8:
            return "Tốt"
        elif self.diem == 7:
            return "Tạm ổn"
        elif self.diem == 5:
            return "Không tốt"
        else:
            return "Chưa được đánh giá được đánh giá"
class TienNghi(models.Model):
    icon = models.ImageField(null=True,blank=True)
    tentiennghi = models.CharField(max_length=200,null=True)
    mota_tiennghi = models.TextField(blank=True,null=True)
    def __str__(self):
        return self.tentiennghi
class SapXepTN(models.Model):
    phong = models.ForeignKey(Phong,on_delete=models.SET_NULL,blank=True,null=True)
    tiennghi = models.ForeignKey(TienNghi,on_delete=models.SET_NULL,blank=True,null=True)
    ngaytrangbi = models.DateTimeField(auto_now_add=True)
class HoaDon(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    trangthaihoanthanh = models.CharField(max_length=200,null=True)
    ngay_gio_dat = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.id)
class ChiTietHoaDon(models.Model):
    phong = models.ForeignKey(Phong,on_delete=models.SET_NULL,blank=True,null=True)
    hoadon = models.ForeignKey(HoaDon,on_delete=models.SET_NULL,blank=True,null=True)
    ngay_gio_nhan = models.DateTimeField()
    ngay_gio_tra = models.DateTimeField()
    soluong = models.IntegerField()
    dongia = models.FloatField()
    @property
    def total_dem(self):
        so_dem = (self.ngay_gio_tra - self.ngay_gio_nhan).days
        return so_dem
    @property
    def total_tien(self):
        tongtien = self.total_dem * self.dongia
        return tongtien
    

travelnest/app/templates/app/blocktimkiem.html
<div class='le'>
  <form class='row box-element' method="POST" action="{% url 'search'%}"  id='homeForm'>
    {% csrf_token %}
    <div class='col-md-3'>
      <input type="text" name="tinh" class="form-control g1" id="search_tinh_id" placeholder="Bạn muốn đến đâu?">
    </div>
    <div class=' col-md-3'>
      <div class='g2'>
        <label for="check-in">Ngày nhận phòng:</label>
        <input onclick="setdate()"  type="datetime-local" id="check-in" name="check-in" min="<?php echo date('Y-m-d'); ?>" required>
      </div>
    </div>
    <div class='col-md-3'>
      <div >
        <label for="check-out">Ngày trả phòng:</label>
        <input onclick="setdate()" type="datetime-local" id="check-out" name="check-out" min="<?php echo date('Y-m-d'); ?>" required>
      </div>
      
    </div>
    <div class='col-md-2 '>
      <button class="uitk-button uitk-button-medium bg-white text-black g3" name='soluong' id="guestCountButton"  type="button" aria-expanded="false" aria-label="Chọn số khách, số phòng" >
        1 khách, 1 phòng
      </button>
      <div class= 'dropdown-menu' id="guestCountDropdown" style="display: none;" aria-hidden="true">
        <div>
          <div class='row'>
            <div class='col'>
              <a class="dropdown-item" href="#">Người lớn</a>
            </div>
            <div class='col'>
              <div class='boxm'>
                <button class='btn_a' type="button" onclick="decrementValue('adult')">-</button>
                <input class='vao' value='1'id="adultCount">
                <button class='btn_a' type="button" onclick="incrementValue('adult')">+</button>
              </div>
            </div>
          </div>
        </div>
        <div>
          <div class='row'>
            <div class='col'>
              <a class="dropdown-item" href="#">Trẻ em</a>
            </div>
            <div class='col'>
              <div class='boxm'>
                <button class='btn_a' type="button" onclick="decrementValue('child')">-</button>
                <input class='vao' value='0' id="childCount">
                <button class='btn_a' type="button" onclick="incrementValue('child')">+</button>
              </div>
            </div>
          </div>
        </div>
        <div>
          <div class='row'>
            <div class='col'>
              <a class="dropdown-item" href="#">Phòng</a>
            </div>
            <div class='col'>
              <div class='boxm'>
                <button class='btn_a' type="button" onclick="decrementValue('room')">-</button>
                <input class='vao' value='1' id="roomCount">
                <button class='btn_a' type="button"onclick="incrementValue('room')">+</button>
              </div>
            </div>
          </div>
        </div>
        <button class="btn_ht" type='button'  id="doneButton">Xong</button>
      </div>
    </div>
    <div class='col-md-1'>
      <input class='g3 search 'id="timkiem" type="submit" value="Tìm">
    </div>
  </form>
</div>

travelnest/app/templates/app/dangky.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}

<section class="h-100 "style="background-color: #F5F7F8;">
    <div class="containernew py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card card-registration my-4">
            <div class="row g-0">
              <div class="col-xl-6 d-none d-xl-block">
                <img src='{% static 'app/images/Q-N.png' %}'
                  alt="Sample photo" class="img-fluid"
                  style="border-top-left-radius: .25rem; border-bottom-left-radius: .25rem;" />
              </div>
              
                <div class="col-xl-6">

                    <div class="card-body p-md-5 text-black">
                      <h3 class="mb-5 text-uppercase">Đăng ký tài khoản</h3>
                      <form method = "POST" action="">
                        {% csrf_token %}
                        <div class="row">
                          <div class='col'>
                              <label class="form-label" for="form3Example8">User Name:</label>
                          </div>
                          <div class='col'>
                              <a class='left'>{{form.username}}</a>
                          </div>
                        </div>
                        <div class="row top">
                          <div class='col'>
                            <label class="form-label" for="form3Example8">First Name:</label>
                          </div>
                          <div class='col top'>
                              <a class='left'> {{form.first_name}}</a>
                          </div>
                        </div>
                        <div class="row top">
                          <div class='col'>
                            <label class="form-label" for="form3Example8">Last Name:</label>
                        </div>
                        <div class='col'>
                            <a class='left'> {{form.last_name}}</a>
                        </div>
                        </div>
                        <div class="row top">
                          <div class='col'>
                            <label class="form-label" for="form3Example8">Email:</label>
                        </div>
                        <div class='col'>
                            <a class='left'> {{form.email}}</a>
                        </div>
                        </div>
                        <div class="row top">
                          <div class='col'>
                            <label class="form-label" for="form3Example8">Password:</label>
                        </div>
                        <div class='col'>
                            <a class='left'> {{form.password1}}</a>
                        </div>
                        </div>
                        <div class="row top">
                          <div class='col'>
                            <label class="form-label" for="form3Example8">Repeat password:</label>
                          </div>
                          <div class='col'>
                            <a class='left'> {{form.password2}}</a>
                          </div>
                        </div>
                        <div class="d-flex justify-content-end pt-3">
                          <button type="submit" class="btn btn-light btn-gt">Đăng ký</button>
                        </div>
                        <p class="text-center text-muted mt-5 mb-0">Đã có tài khoản? <a href="{%url 'dangnhap'%}"
                          class="fw-bold text-body"><u>Đăng nhập tại đây!</u></a></p>
                      </form>
                    </div>

                </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

travelnest/app/templates/app/dondatphong.html
{% extends "app/base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
<div class='l '>
    <a href="#" onclick="goBack();"><img class='icon-back' src='{% static 'app/images/icon/back.png' %}'></img></a>
    {% for hoadon in hoadons %}
        <div class='top1'>
            <h4><strong>Mã số hóa đơn: {{ hoadon.id }}</strong></h4>
            <p>Ngày đặt: {{ hoadon.ngay_gio_dat }}</p>
            <!-- Thêm các thông tin khác của hóa đơn ở đây -->
            {% for chitiethoadon in hoadon.chitiethoadon_set.all %}
            <ul>
                <li>Khách sạn: {{ chitiethoadon.phong.khachsan.tenkhachsan }}</li>
                <li>Địa chỉ: {{ chitiethoadon.phong.khachsan.diachi }}</li>
                <li id= 'phong'>Phòng: {{ chitiethoadon.phong.loaiphong.tenloaiphong }}</li>
                <li>Ngày nhận: {{ chitiethoadon.ngay_gio_nhan }}</li>
                <li>Ngày trả: {{ chitiethoadon.ngay_gio_tra }}</li>
                <li>Tổng tiền: {{ chitiethoadon.total_tien|floatformat:2|intcomma}}</li>  
            </ul>
            <div class="d-flex justify-content-left">
                <button type="button" class="btn btn-light btn-lg me-2 danhgia" data-bs-toggle="modal" data-bs-target="#exampleModal" data-phong="{{chitiethoadon.phong.id }}">
                    Đánh giá
                </button>
                
            </div>
            {% endfor %} 
        </div>
    {% endfor %}
    <form method='POST' action="">
        {% csrf_token %}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Đánh giá khách sạn</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="phong_id">
                    <div>
                        <h3>Mức điểm:</h3>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="10" checked>
                            <label class="form-check-label" for="exampleRadios1" >
                            10
                            </label>
                            <label> (Tuyệt vời)</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="8">
                            <label class="form-check-label" for="exampleRadios2" >
                            8
                            </label>
                            <label>(Tốt)</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios3" value="7">
                            <label class="form-check-label" for="exampleRadios3" >
                            7
                            </label>
                            <label>(Tạm ổn)</label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios4" value="5">
                            <label class="form-check-label" for="exampleRadios4" >
                            5
                            </label>
                            <label>(Không tốt)</label>
                        </div>
                    </div>
                    <div>
                        <h3>Bình luận:</h3>
                        <textarea class="form-control" name='binhluan' id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>
    
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                <input type="submit"  class="btn btn-primary" value="Lưu đánh giá">
                </div>
            </div>
            </div>
        </div>
    </form>

</div> 
<br></br></br></br></br></br></br>
{% endblock content %}

travelnest/app/templates/app/home.html
{% extends "app/base.html" %}
{% load static %}
{% load humanize %}

{% block content %}
{% include "app/blocktimkiem.html" %}
<div class='row l kkp'>
  <a>Khám phá thêm trong năm 2023. Bạn sớm đăng nhập để có những khuyến mãi hấp dẫn.</a>
  <a class='bd' >Bắt đầu nào</a>
</div>

    <div class='le tren'>
        <h3><strong> Địa điểm đang thịnh hành</strong></h3>
        <p>Du lịch để tận hưởng vẻ đẹp thiên nhiên, văn hóa đa dạng </p>
        <div class= 'row'>
          {% for top2 in top_2_tinhs  %}
            <div class="container-1">
                <div class='text-overlay'><b>{{top2.tentinh}}</b></div>
                <a class="tinh-item" data-tinh-id="{{ top2.id }}" data-tinh-name="{{ top2.tentinh }}"><img class="thumbnail" src="{{top2.anhtinh.url}} "></a>
            </div>
          {% endfor %}
        </div>
        <div class= 'row t' >
            {% for top3 in top_3_tinhs  %}
            <div class=" container1">
                <div class='text-overlay'><b>{{top3.tentinh}}</b></div>
                <a class="tinh-item" data-tinh-id="{{ top3.id }}" data-tinh-name="{{ top3.tentinh }}"><img class="thumbnail1" src="{{top3.anhtinh.url}} "></a>
            </div>
            {% endfor %}
        </div>

    </div>

<div class='le tren'>
  <h3><strong>Khám phá Việt Nam</strong></h3>
  <p>Cuộc hành trình tuyệt vời để tham quan và khám phá vẻ đẹp tự nhiên của quê hương</p>
  <div class='row'>
    <button id="prev"><</button>
    <div class="image-slider">
      <div class="image-list" id="image-list">
        {% for tinh in tinh_data %}
        <div class="tinh-item" data-tinh-id="{{ tinh.id }}" data-tinh-name="{{ tinh.tentinh }}">
            <img class="image" src="{{ tinh.anhtinh.url }}" alt="{{ tinh.tentinh }}">
            <h6><strong>{{ tinh.tentinh }}</strong></h6>
            <h6>{{ tinh.num_hotels }} chỗ nghỉ</h6>
        </div>
        {% endfor %}
      </div>
    </div>
    <button id="next">></button>
  </div>
</div>

<div class='l tren'>
  <h3><strong>Ưu đãi cuối tuần</strong></h3>
  <p>Với mức giá ưu đãi hấp dẫn, tiết kiệm</p>
  <div class='row'>
    <button class='btn_pn' id="prev2"><</button>
    <div class="image-slider1">
      <div class="image-list" id="image-list2">
        {% for tinh in tinh_data %}
        <div class="card col card_w trai" >
          <a href="{%url 'ks'%}?khachsan_id={{tinh.khachsan_set.first.id}}"><img src="{{tinh.khachsan_set.first.anhkhachsan.url}}" class="card-img-top" alt="..." height='200px'></a>
          <div class="card-body">
            <p class="card-text">{{tinh.khachsan_set.first.diem_trung_binh}}/10 {{tinh.khachsan_set.first.get_danh_gia_tb}}</p>
            <h5 class="card-title">{{tinh.khachsan_set.first.tenkhachsan}}</h5>
            <a>{{tinh.tentinh}}</a>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"> 
              <a>{{tinh.khachsan_set.first.phong_set.first.giaphong}} VND</a></br>
              <h6>Mỗi đêm</h6>
            </li>
            <li class="list-group-item">Không phụ thu</li>
            <li class="list-group-item">Không thuế</li>
          </ul>
          <div class='card-body ks-item' data-ks-id="{{ tinh.khachsan_set.first.id }}">
            <button class='btntim'>Tìm phòng</button></a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <button id="next2">></button>
  </div>
</div>
</br>
{% endblock content %}

travelnest/app/templates/app/listkhachsan.html
{% extends "app/base.html" %}
{% load static %}

{% block content %}
{% include "app/blocktimkiem.html" %}

<div class='l'>
  <a class='t-link' href="{% url 'home'%}">Trang chủ </a>
  <span> > </span>
  <a class='t-link' href="{% url 'ds' %}?tinh_id={{ tinh_id }}&tinh_name={{ tinh_name }}">{{ tinh_name }}</a>
  <span> > </span>
  <a>Kết quả tìm kiếm</a>
</div>

<div class='le'>
    <h3>{{ tinh_name }}: Tìm thấy {{khachsans.count}} chỗ nghỉ</h3>
    {% for khachsan in khachsans  %}
    <div class='box ks-item' data-ks-id="{{ khachsan.id }}" data-ks-name="{{ khachsan.tenkhachsan }}">
        <div class='row'>
            <div class="col-sm-3 image-container">
                <img class="thumbnail4" src="{{khachsan.anhkhachsan.url}}">
                <a href="#" class="heart"><img src="{% static 'app/images/heart1.png' %}"></a>
            </div>
            <div class="col-sm-6">
                <h3><strong>{{khachsan.tenkhachsan}}</strong></h3>
                <div>
                    <a><h6>{{khachsan.diachi}}</h6></a>
                    <h6>{{khachsan.mota}}</h6>
                </div>
                    <h4><strong>{{ khachsan.phong_set.first.loaiphong.tenloaiphong}}</strong></h4>
                    <h6>* {{khachsan.phong_set.first.loaigiuong}}</h6>
                    <h6>* {{khachsan.phong_set.first.mota}}</h6></br>
              </div>
            <div class="col-sm-3 container4">
                <div class='nd'>
                  <div >
                      <h5><strong>{{khachsan.get_danh_gia_tb}}<strong></h5>
                      <h6 >{{khachsan.sum_danh_gia}} đánh giá</h6>
                  </div>
                  <button class='diem'>{{khachsan.diem_trung_binh}}</button>
                </div>
                <div class='bottom-right'>
                  <h6>1 đêm, {{khachsan.phong_set.first.soluongnguoi}} người</h6>
                  <h3>{{khachsan.phong_set.first.giaphong|floatformat:0}} VND</h3>
                  <button class='btn_trong'>Xem chỗ trống > </button></a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<div class='l'>
  <div class='boxm2'>
    <div class='row'>
      <div class='col-md-4'>
        <a ><img class='anhgt' src='{% static 'app/images/QN.png' %}'></img></a>
      </div>
      <div class='col-md-5'>
        <h3><strong>Hưởng nhiều quyền lợi hơn với web TravelNest</strong></h3>
        <h6>Tiết kiệm tại một số khách sạn và nhận gấp đôi số điểm khi đặt qua app. Với ưu đãi trên app của chúng tôi, bạn có thể tiết kiệm để đi được nhiều hơn và quản lý mọi thứ trong khi đang di chuyển.</h6>
        <h6><strong>Quét mã QR bằng camera trên thiết bị của bạn để tải app của chúng tôi</strong></h6>
      </div>
      <div class='col-md-3'>
        <img class='anhqr' src='{% static 'app/images/travelnest.png' %}'></img>
  
      </div>
    </div>
  </div>
  <div class='textend'>
  </div>
</div>
{% endblock content %}

travelnest/app/templates/app/nammoi.html
<h1>Chúc mừng năm mới 2024</h1>
<p>Tôi là Nhi, năm mới tôi hi vọng tôi được may mắn trong công việc lẫn tình cảm, giao lưu hòa nhập được với đồng nghiệp không taọ gánh nặng cho gia đình.
<p>Hi vọng mọi chuyện sẽ thành công với tôi.
<p>Chúc gia đình sẽ được bình an.
<p>Chúc cuộc sống sẽ trở nên đơn giản hơn

travelnest/app/templates/app/search.html
{% extends "app/base.html" %}
{% load static %}
{% block content %}
{% include "app/blocktimkiem.html" %}
<div class='l'>
  <a class='t-link' href="{% url 'home'%}">Trang chủ </a>
  <span> > </span>
  <a class='t-link' href="#">{{tinh}}</a>
  <span> > </span>
  <a>Kết quả tìm kiếm</a>
</div>
<div class='le'>
  <h3>{{tinh}}: Tìm thấy {{khachsans.count}} chỗ nghỉ</h3>
  {% for khachsan in khachsans  %}
  <div class='box ks-item' data-ks-id="{{ khachsan.id }}" data-ks-name="{{ khachsan.tenkhachsan }}"> 
      <div class='row'>
        <div class="col-sm-3 image-container">
            <img class="thumbnail4" src="{{khachsan.anhkhachsan.url}}">
            <a href="#" class="heart"><img src="{% static 'app/images/heart1.png' %}"></a>
        </div>
        <div class="col-sm-6">
            <h3><strong>{{khachsan.tenkhachsan}}</strong></h3>
            <div>
                <a><h6>{{khachsan.diachi}}</h6></a>
                <h6>{{khachsan.mota}}</h6>
            </div>
                <h4><strong>{{ khachsan.phong_set.first.loaiphong.tenloaiphong}}</strong></h4>
                <h6>* {{khachsan.phong_set.first.loaigiuong}}</h6>
                <h6>* {{khachsan.phong_set.first.mota}}</h6></br>
          </div>
          <div class="col-sm-3 container4">
            <div class='nd'>
                <div >
                    <h5><strong>{{khachsan.get_danh_gia_tb}}<strong></h5>
                    <h6 >{{khachsan.sum_danh_gia}} đánh giá</h6>
                </div>
                <button>{{khachsan.diem_trung_binh}}</button>
                </div>
              <div class='bottom-right'>
                  <h6>1 đêm, {{khachsan.phong_set.first.soluongnguoi}} người</h6>
                  <h3>{{khachsan.phong_set.first.giaphong}} VND</h3>
                  <button class='btn_trong'>Xem chỗ trống > </button></a>
              </div>
          </div>
      </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}